README.md
=> First commit 

README.md
Let me know what you think, and feel free to spice it up however you see fit as well :)
=> Adding inital styling and images to readme

docs/contributing.md
This PR was created to add contribution guidelines to keep the code and documentation consistent, clean and readable throughout the project.
It is just the initial draft, please review it and leave your comments. 
resolve #33
=> [docs] Add contributions guidelines

src/controllers/user.ts, src/helpers/apiError.ts
+ Added error handler to backend so we can use it to handle errors. 
+ Handled error for delete user route.
=> [FEAT] Add error handler

cspell.json
Add dictionary to align spelling and naming across contributors.
=> [feat] Add dictionary

cspell.json, src/controllers/user.ts, src/services/user.ts, src/types.ts
This PR adds update functionality for the following user properties:
- `first_name`
- `last_name`
- `profile_image`
- `profile_text`
Let me know if I need to include `base_address`, I don't know what is that.
**I do not allow the user to change emails considering we only have google login.**
I also added type for `User`. And the error handling will need to be improved in the future.
I saw Mike's comment about refactoring Chiran's PR, please let me know if I need to refactor this one as well.
close issue #25
=> [FEAT] Add update functionality for user

src/controllers/user.ts, src/services/user.ts
Moved response to user from service to controller.
=> [refactor] Handle response for delete user route

src/controllers/event.ts, src/services/event.ts
=> [feat] Delete event

src/controllers/event.ts, src/routers/event.ts, src/services/event.ts
|Read events | route |  controller | service |
|-------|-------|-------|-------|
|all| X | X | X |
|byId| X | X | X |
|byCategory| X | X | X |
=> [feat] Add read to events

.eslintrc, jest.config.js, package.json, test/controllers/user.test.ts
+ Changed npm test script
+ Installed a few packages
+ Implemented one test which should be removed later
There is an issue with eslint and jest:
```
error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: test/controllers/user.test.ts.
The file must be included in at least one of the projects provided
```
Currently it solved by adding `"createDefaultProgram": true` into `parserOptions` in `.eslintrc`. 
`"createDefaultProgram": true` will be depreciated later, we should find another solution.
=> [feat] Setup jest for server

src/controllers/event.ts, src/routers/event.ts, src/services/event.ts
Refactored to pass only event id to the eventService not request/response.
=> Feature delete event

src/controllers/event.ts, src/services/event.ts
=> [feat] Edit event

client/src/SCSS/_config.scss, src/services/event.ts
SCSS-configuration – google fonts import, global variables for colors, fonts, and font-sizes
=> [Feat] Create SCSS-config

test/controllers/user.test.ts, test/db/db-helper.ts
Dbhelper is adjusted due changes in [PR88](https://github.com/MikeVedsted/JoinMe/pull/88)
Remember to pull new db from heroku and change ur `.env` file if needed.
Didn't pass `npm run lint` cuz there are some issues in client folder. Commited with no verify.
=> [fix] Adjust dbhelper for jest

client/src/components/EventForm/index.tsx, client/src/components/GoogleAutoComplete/index.tsx, client/src/components/GoogleUserLogin/index.tsx, client/src/components/Modal/index.tsx, client/src/components/Navbar/index.tsx, client/src/index.tsx
=> [CHORE] Configure react-cookies for auth

client/src/components/Button/index.tsx, client/src/pages/LandingPage/index.tsx, client/src/types.ts
prop name 'style' was clashing with native property.
Done:
=> Bug button prop style

client/src/components/NavDropdownFunction/index.tsx, client/src/components/NavDropdownLink/index.tsx, client/src/types.ts
Adding reusable dropdown item components for links and functions separately.
Related issues:
#142 and #114
=> [FEAT] Add dropdown items

client/src/components/NavDropdown/NavDropdown.scss, client/src/components/NavDropdown/index.tsx, client/src/components/Navbar/index.tsx, client/src/types.ts
Adding dropdown container, styles and logout functionality to feed the item component. 
Related PR:
#143 
Related issues:
#141 and #114
=> [FEAT] Add nav dropdown container

client/src/components/EventSearch/EventSearch.scss, client/src/components/EventSearch/index.tsx
It is not much here. just collected dropdown input and button. The slider still needs to be added. We can refactor it later.
=> [feat] Add event search component

client/src/App.tsx, client/src/Routes.tsx, client/src/components/Button/Button.scss, client/src/components/Button/index.tsx, client/src/components/Event/index.tsx, client/src/components/EventForm/eventForm.scss, client/src/components/MyEventsSidebar/MyEventsSidebar.scss, client/src/components/MyEventsSidebar/index.tsx, client/src/components/NavDropdown/index.tsx, client/src/pages/LandingPage/index.tsx, client/src/pages/MyEventsPage/MyEventsPage.scss, client/src/pages/MyEventsPage/index.tsx, client/src/types.ts
Step 1:  Set up with location and history, so we can render view conditionally on the page, without having to re-render everything.
UPDATE:
Step 2: Added my-events page and converted to draft. 
More or less ready but lacking the actual data to display.
Please still give some feedback and ask questions if there's something you'd like to see :)
Related issue: 
#125 and #130
=> [FEAT] Add MyEvents page and sidebar component

src/services/user.ts, src/types.ts
Upon merging, get request to find user by Id will return:
{
"user_id": "1f224f321-17f3-48e5-a155-db1e92aabcad",
"first_name": "Ngan",
"last_name": "Dao",
"email": "nd@integrify.io",
"profile_image": "https://lh3.googleusercontent.com",
"profile_text": null,
"base_address": "97f23153-1bb9-415a-b575-84c1ab6b76d5",
"created_at": "2020-12-15T11:56:45.504Z",
"date_of_birth": null,
"gender": null,
"address_id": "97f23124-1bb9-415a-b575-84c1ab6b76d5",
"street": "Street3",
"number": 3,
"postal_code": 33333,
"city": "Oulu",
"country": "Finland",
"lat": "58.1234567",
"lng": "50.1234567",
"interests": [
"Football",
"Running"
],
}
Close issue #116
=> [feat] Update findUserById Service

src/controllers/user.ts, src/services/user.ts, src/types.ts
Included all new field options to update service, so back end matches front end
=> [CHORE] Refactor update user service

src/controllers/comment.ts, src/routers/comment.ts, src/services/comment.ts
=> [FEAT] Add Create operation for comment

src/controllers/comment.ts, src/routers/comment.ts, src/services/comment.ts
=> [FEAT] Add Update to comment BE

client/src/pages/LandingPage/index.tsx
Deleted user request cuz this route will be protected in backend, so it will not work plus I am not sure if we will allow users to see list of all users.
=> [refactor] Remove user request in landing page

client/src/pages/LandingPage/index.tsx
It is probably not needed, but I just wanted to close the issue with PR.
=> [feat] Close login modal on success

client/src/pages/LandingPage/index.tsx, src/controllers/user.ts, src/routers/user.ts, src/services/user.ts
@Rostislav013 I think this is a better solution to what you were trying to achieve in #204
=> Rostislav013 refactor/landing page

client/src/components/Event/Event.scss, client/src/components/Event/index.tsx, client/src/components/EventManageDropDown/EventManageDropDown.scss, client/src/components/EventManageDropDown/index.tsx, client/src/types.ts, client/src/util/fontawesome.ts
=> [Feat] Add event manage options

client/src/Routes.tsx, client/src/components/AccountForm/index.tsx, client/src/components/Event/index.tsx, client/src/components/EventParticipant/index.tsx, client/src/components/Footer/index.tsx, client/src/hooks/useEventDisplay.tsx, client/src/hooks/useUserDisplay.tsx, client/src/pages/Homepage/index.tsx, client/src/pages/LandingPage/index.tsx, client/src/types.ts
Fix broken paths and align requests
=> [FIX] Align links and requests

client/src/Routes.tsx
Redirect invalid routes to /get-started, which already has a redirect
=> [FEAT] Handle 404s

client/src/components/EventJoinRequest/EventJoinRequest.scss, client/src/components/EventJoinRequest/index.tsx, client/src/types.ts, client/src/util/fontawesome.ts
=> [Feat] Add event join request component

client/src/components/EventList/EventList.scss, client/src/components/EventList/index.tsx, client/src/hooks/useHostedEvents.tsx, client/src/pages/ProfilePage/index.tsx, client/src/types.ts
Reusable listing component for events, including optional title.  Styled to match profile page but styles might need to be re-aligned across site
=> [feat] Add EventList component

client/src/components/Modal/Modal.scss, client/src/components/Modal/index.tsx, client/src/pages/LandingPage/LandingPage.scss, client/src/pages/LandingPage/index.tsx
=> [Fix] Add scroll function to modal

client/src/components/EventList/EventList.scss, client/src/hooks/useParticipatingEvents.tsx, client/src/pages/MyEventsPage/index.tsx, src/controllers/user.ts, src/routers/user.ts, src/services/user.ts
Set up BE to handle request, add hook, add in EventList with confirmed events for MyEvents
=> [feat] Add participating events

client/src/hooks/useInterestedEvents.tsx, client/src/pages/MyEventsPage/index.tsx, src/controllers/user.ts, src/routers/user.ts, src/services/user.ts
Set up BE to handle interested events request, add hook, add in interested list to MyEvents page
=> [feat] Add interested events to MyEvents

client/src/components/Event/Event.scss, client/src/components/Event/index.tsx, client/src/components/EventList/index.tsx, client/src/pages/Homepage/index.tsx, client/src/types.ts, src/controllers/event.ts, src/routers/event.ts, src/services/event.ts
=> [feat] Add join requests

client/src/components/Event/Event.scss, client/src/components/Event/index.tsx, client/src/components/EventList/index.tsx, client/src/pages/Homepage/index.tsx, client/src/types.ts, src/controllers/event.ts, src/routers/event.ts, src/services/event.ts, src/services/user.ts
Bonus: 
Refactor long query strings to be their own constants.
=> [refactor] Resolve undefined values in Events component

client/src/pages/ProfilePage/index.tsx, src/controllers/user.ts, src/routers/user.ts, src/services/user.ts
Add route for public profile and protect route with all information
=> [feat] Add public profile route

client/src/components/Event/index.tsx, client/src/components/EventUpdateForm/EventUpdateForm.scss, client/src/components/EventUpdateForm/index.tsx, client/src/hooks/useEventDetails.tsx, client/src/pages/EventEditPage/index.tsx, client/src/types.ts
@Chiranjibichapagain note that I have changed the base branch on your PR #244 Please merge yours before this one.
With these changes, I am
=> [fix] Addition to edit Event

src/services/event.ts
=> [fix] Unable to create event

client/src/components/GoogleAutoComplete/index.tsx
Fixing language bug and simplifying AutoResponse
Could those of you with device languages other than English please check if the response is now in English?
=> [fix] Refactor address response handling

client/src/SCSS/_config.scss, client/src/components/EventHosted/HostedEvent.scss, client/src/components/EventHosted/index.tsx, client/src/components/EventInterested/EventInterested.scss, client/src/components/EventInterested/index.tsx, client/src/components/EventList/index.tsx, client/src/pages/MyEventsPage/MyEventsPage.scss, client/src/pages/MyEventsPage/index.tsx, client/src/types.ts
No need for review - this a draft so far.
I will request reviews once done. 
**So far:**
**To do:**
Close #263
=> [feat] Add interested event display component

client/src/SCSS/_config.scss, client/src/components/Event/Event.scss, client/src/components/Event/index.tsx, client/src/components/EventConfirmed/EventConfirmed.scss, client/src/components/EventConfirmed/index.tsx, client/src/components/EventHosted/HostedEvent.scss, client/src/components/EventHosted/index.tsx, client/src/components/EventInterested/EventInterested.scss, client/src/components/EventInterested/index.tsx, client/src/components/EventList/index.tsx, client/src/pages/Homepage/index.tsx, client/src/pages/MyEventsPage/MyEventsPage.scss, client/src/pages/MyEventsPage/index.tsx, client/src/types.ts, cspell.json
No need for review - this a draft so far.
=> Add confirmed events

client/src/components/Event/Event.scss, client/src/hooks/useHostedEvents.tsx, client/src/pages/ProfilePage/ProfilePage.scss, client/src/pages/ProfilePage/index.tsx, client/src/util/ProtectedRoute.tsx, src/controllers/user.ts, src/helpers/generateToken.ts, src/middlewares/authentication.ts, src/routers/user.ts, src/services/user.ts, src/util/secrets.ts
Implement refresh token in private route.
To test out, remember to add `JWT_REFRESH_SECRET` variable to your .env
Currently I set the access token to expire in 5 mins so you have shorter waiting time. Later on I can extend it to 1hr.
Update 1: It is possible to refresh page and get the refreshed token now. 
Update 2: A new access token is now generated from isAuthenticated middleware. Also, if refreshToken expired, I removed the user from cookies (same with logout function). Please inform me anything you'd like to improve!
Close #220
=> [feat] refresh token

client/src/components/AccountForm/index.tsx, client/src/components/Event/index.tsx, client/src/components/EventCommentInput/index.tsx, client/src/components/EventForm/index.tsx, client/src/components/EventJoinRequest/index.tsx, client/src/components/EventList/index.tsx, client/src/components/EventParticipant/index.tsx, client/src/components/EventParticipantsAndRequests/index.tsx, client/src/components/EventUpdateForm/index.tsx, client/src/components/GoogleUserLogin/index.tsx, client/src/hooks/useEventComments.tsx, client/src/hooks/useEventParticipants.tsx, client/src/hooks/useEventRequests.tsx, client/src/hooks/useParticipatingEvents.tsx, client/src/hooks/useRequestedEvents.tsx, client/src/pages/Homepage/index.tsx, client/src/pages/MyEventsPage/index.tsx, client/src/types.ts, src/controllers/event.ts, src/controllers/request.ts, src/controllers/user.ts, src/db/queries.ts, src/routers/comment.ts, src/routers/event.ts, src/routers/request.ts, src/routers/user.ts, src/services/event.ts, src/services/request.ts, src/services/user.ts
**Back end**
**Front end**
**Back end**
**Front end**
=> [feat] Add join request handling

client/src/components/EventSearch/index.tsx, client/src/components/FormDropdownField/index.tsx, client/src/components/FormSlider/index.tsx, client/src/hooks/useEventDisplay.tsx, client/src/pages/Homepage/index.tsx, client/src/types.ts, src/controllers/event.ts, src/services/event.ts, src/types.ts
=> [Feat] Search event

client/src/SCSS/_config.scss, client/src/components/Navbar/Navbar.scss, client/src/components/Navbar/index.tsx
DRY up nav styles and divs in component. 
Adding mixins that will be needed for other refactors as well. 
close #163
=> [refactor] nav styles

client/src/SCSS/_config.scss, client/src/components/EventComment/EventComment.scss, client/src/components/EventComment/index.tsx, client/src/types.ts
Add link, DRY styles, use ProfileImage
=> [refactor] EventComment

client/src/components/ModalMessageCancel/ModalMessageCancel.scss, client/src/components/ModalMessageCancel/index.tsx
=> [refactor] ModalCancelMessage

client/src/SCSS/_config.scss, client/src/components/EventSearch/EventSearch.scss, client/src/components/EventSearch/index.tsx
Move styles from homepage, DRY styles
=> [refactor] EventSearch

client/src/SCSS/_config.scss, client/src/components/EventTitle/EventTitle.scss
=> [refactor] EventTitle

client/src/components/Event/Event.scss, client/src/components/Event/index.tsx, client/src/components/EventTitle/EventTitle.scss, client/src/pages/Homepage/Homepage.scss
=> [refactor] Event component

client/src/SCSS/_config.scss, client/src/components/Event/Event.scss, client/src/components/Event/index.tsx, client/src/components/EventImage/EventImage.scss, client/src/components/EventTitle/EventTitle.scss, client/src/pages/Homepage/Homepage.scss
Adjust styling to event component
=> [refactor] EventImage

client/src/SCSS/_config.scss, client/src/components/Event/Event.scss, client/src/components/Event/index.tsx, client/src/components/EventDataBox/EventDataBox.scss, client/src/components/EventDataBox/index.tsx, client/src/components/EventImage/EventImage.scss, client/src/components/EventTitle/EventTitle.scss, client/src/pages/Homepage/Homepage.scss, client/src/types.ts, client/src/util/helperFunctions.tsx
simplify component, add dynamic styling, align in event component, fix uneven icon spacing, add format address helpe rfunction
=> [refactor] EventDatabox

client/src/components/NavDropdown/NavDropdown.scss, client/src/components/NavDropdown/index.tsx
=> [refactor] NavDropdown

client/src/Types/redux.ts, client/src/redux/actions/index.ts, client/src/redux/actions/loading.ts, client/src/redux/reducers/loading.ts
Add types, actions, and reducers
=> [chore] Configure loading state handling

client/src/components/GoogleLogin/index.tsx
Implement dispatch, move checkNew to useEffect
=> [refactor] GoogleLogin

client/src/Routes.tsx, client/src/Types/objects.ts, client/src/Types/redux.ts, client/src/components/GoogleLogin/index.tsx, client/src/hooks/useUser.ts, client/src/pages/Homepage/index.tsx, client/src/redux/actions/auth.ts, client/src/redux/actions/ui.ts, client/src/redux/actions/user.ts, client/src/redux/reducers/auth.ts, client/src/redux/reducers/ui.ts, client/src/redux/reducers/user.ts
Add types, actions, reducers, update dependents
=> [chore] Add Auth state handling

client/src/Types/componentProps.ts, client/src/components/Event/Event.scss, client/src/components/Event/index.tsx, client/src/components/EventManageDropDown/EventManageDropDown.scss, client/src/components/EventManageDropDown/index.tsx
DRY styles, move functions, modal from event
=> [refactor] EventManageDropdown

client/src/components/ModalLogin/ModalLogin.scss, client/src/components/ModalLogin/index.tsx
=> [feat] Add login modal content

client/src/Types/componentProps.ts, client/src/components/CircleContainer/CircleContainer.scss, client/src/components/CircleContainer/index.tsx, client/src/pages/LandingPage/LandingPage.scss, client/src/pages/LandingPage/index.tsx
=> [feat] Add CircleContainer

client/src/SCSS/_fonts.scss, client/src/SCSS/_sizing.scss, client/src/components/Footer/Footer.scss, client/src/components/Footer/index.tsx, client/src/components/Navbar/Navbar.scss
=> [refactor] Footer

client/src/pages/EventEditPage/EventEditPage.scss, client/src/pages/EventEditPage/index.tsx
DRY styles, get info from store
=> [refactor] EditEventPage

client/src/Types/componentProps.ts, client/src/Types/objects.ts, client/src/components/AccountForm/index.tsx, client/src/components/EventForm/index.tsx, client/src/components/EventSearch/index.tsx, client/src/components/FormInputField/InputField.scss, client/src/components/GoogleAutoComplete/index.tsx, client/src/redux/actions/error.ts
Add error handling, add label and currentAddress display
=> [refactor] GoogleAutoComplete

src/services/event.ts
Include count of ep_id in query
=> [feat] Add participant count to all events res

client/src/components/AccountForm/index.tsx, client/src/pages/ProfileEdit/ProfileEdit.scss, client/src/pages/ProfileEdit/index.tsx
Get userinfo from store, DRY styles, add breakpoints, simplify component
=> [refactor] ProfileEdit
